//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_MyAssets/Misc/InputActions/IA_Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @IA_Player: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @IA_Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""IA_Player"",
    ""maps"": [
        {
            ""name"": ""PlayerAction"",
            ""id"": ""cdf64783-f9b4-4f3e-b543-ffb6c01cd012"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""7eff2f9d-daf2-46af-b36b-655cfab95cbe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""c9fafe89-4a67-4523-b9da-2c84f891dbb7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wire"",
                    ""type"": ""Button"",
                    ""id"": ""a8213568-675a-4e6f-9131-535bee700080"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Assassinate"",
                    ""type"": ""Button"",
                    ""id"": ""c806ddfd-84d4-4e85-a89f-bef7e0450b60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""9c0a6b18-ce2b-45b3-b0ff-aa956f6fb92b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e890f7ba-64cc-410b-9e09-488a0d2492e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aiming"",
                    ""type"": ""Button"",
                    ""id"": ""9cae9f6c-8c2b-494f-bb9e-7852d26c88fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""859511e1-e30c-4dd8-b77f-57aff93c7f99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""54119653-70fc-4afb-a567-2aa127137507"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Clairvoyance"",
                    ""type"": ""Button"",
                    ""id"": ""cd97813d-cb75-4f64-841e-aebdc92a9a1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GamepadAxis"",
                    ""type"": ""Value"",
                    ""id"": ""2bba83df-f007-47db-98e7-2288eaedc01d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4e7511f7-a5d2-43ac-b6f6-be1fbbe59619"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a6f81a4f-a7f7-4e04-9f72-ba738f110cec"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8ac7bc98-ea76-41b8-9779-5943821fe4cb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""88e87f66-71c8-4672-9ae7-797aa295fda1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2ac94f8d-0721-47bc-aa86-809307221d9a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f71cfdbf-68ae-4595-9a21-c8ac72ba55a1"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bb6b0dd-0548-42cb-bbbd-ed203beb2a2a"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Wire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c61f962-9c27-473a-87d5-c3e9006e355a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Assassinate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a9207ea-1833-49b1-ace5-d4b438f779ed"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Assassinate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""636f800d-97fe-4c29-8365-be420d420570"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de02b45b-273f-40bd-ac24-67039bf9a21e"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d77d8df-4536-4b32-b3e4-6c9db733c620"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6134265e-1dfc-4150-bc5d-997504f1bd61"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""584aabb4-5a3a-4af4-8ebd-e0e647189054"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4869736a-2de2-4c12-bbac-c8d31b9e1cc0"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76e3e850-9aa6-43a4-b704-d5d8148948bb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6de390e9-b81d-491d-8bd4-ea32341c0475"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51f72d70-ee4b-45f3-a958-098a436c5d5e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2006c4e-50b1-4058-b282-263e1f2a77e2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8f41f95-3436-4473-9ab9-6822a3ca4d67"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7115826b-1e81-418d-b40e-fdb1f35f5548"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e879c5f-9102-499e-8153-04f2df91fb93"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Clairvoyance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4522cabe-cb9b-4d56-a54a-6780fd73ee8a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Clairvoyance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f9499a2-9e8d-40ee-a6ff-0aa6eaa5482f"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""GamepadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""HideAction"",
            ""id"": ""2621908e-f51a-4096-9046-1185fe0701d1"",
            ""actions"": [
                {
                    ""name"": ""Peek"",
                    ""type"": ""Button"",
                    ""id"": ""a6666a57-2a62-4ba0-92f6-80f163b5d1f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Value"",
                    ""id"": ""b45a26a2-7f21-48b0-8864-0396895e0660"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseAxis"",
                    ""type"": ""Value"",
                    ""id"": ""8ba2651e-c9f9-49c6-a115-35e3afb74ad6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PeekGamepadAxis"",
                    ""type"": ""Value"",
                    ""id"": ""9dd6c878-8491-4de3-8060-17f423f82046"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""53531b06-552a-4ac4-b3db-2bef8a7c2b3d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5c112874-54f1-4610-a165-940767c902ed"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Peek"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b44584c3-caa3-4c2a-b776-8b9e010cc28d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Peek"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Move"",
                    ""id"": ""e6943423-3ddf-4641-b261-249eae3d6a99"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c4d0284d-7a9c-4f1b-a9ef-29a5bb079884"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""441d1f8b-40b6-4781-95ba-41e452ae4efa"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ab5443cd-8732-4535-8cd7-3f83ef1ea397"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5a3db6ef-0e2c-4c8e-98a4-3249d0d7665d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""49134788-8a4a-4565-bcbe-bb3e836f6f49"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83069f03-721d-40e1-9090-3ccf8018a0ea"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MouseAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb7ce27d-14bc-4942-83b1-305ba265a41b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PeekGamepadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79526755-b3f6-4287-ba70-a9fe76e1e586"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06f517ca-1fd0-4a93-813c-30f2c032f4eb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SettingAction"",
            ""id"": ""684b9a7b-9cd6-4dde-99a8-2dc6278ec578"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""07be31d9-1a86-40a5-9d13-18960f21c57c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""e0a0c854-a427-48d7-841a-3911f64cacc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TabMove"",
                    ""type"": ""Button"",
                    ""id"": ""63379582-1199-4b83-9528-d0bc7d0bcd7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5476f300-85eb-476d-aec9-d65764a59bb1"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91045f8d-9186-480c-acfc-af8750965b94"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f9c6bb3-1b58-4c73-b283-535586a5d2a1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c489ffd2-1e44-458b-b45a-062896ee9d30"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""a7bea637-7cf6-4cd5-a759-f662964c4f92"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6c33735a-a64c-4011-a766-8d6b2e656594"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""TabMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e2937872-a601-4c8f-97c4-9be67f0ad1b2"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""TabMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard Arrow"",
                    ""id"": ""6e4348f2-414e-4aba-93db-81e619bd2abb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""63d7b25b-21ee-46a5-8b13-aaf94e1e3cd0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""TabMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""fe5721b0-6950-4ffe-b2cc-1297ea7b02dd"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""TabMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""a5eb688e-a751-40d0-8f35-295fa8eea124"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""344e873a-93cf-4e2e-ba44-7eaad452f6ee"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""TabMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7a19a501-ef85-4322-8a3b-025ee009c4ad"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""TabMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""SettingDetailAction"",
            ""id"": ""512dbe2a-32f4-42b0-af34-ed5549f4b482"",
            ""actions"": [
                {
                    ""name"": ""DetailSubmit"",
                    ""type"": ""Button"",
                    ""id"": ""97ae95ae-3567-4c3e-9b72-6e23b0ce3674"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DetailMove"",
                    ""type"": ""Value"",
                    ""id"": ""fcac0c52-eb10-47ae-8e2d-84dfd96021d3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""31da5849-dbb8-442c-9f15-0dbabfed7cc3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""131d1477-bb9a-4076-acab-9f7c5ac8ffd3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DetailSubmit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4260c850-a1f4-4bfa-ac03-2c925cb8b038"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailSubmit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a00377bc-99a1-4a82-bce4-2749c2acf527"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b711a599-ba04-4033-be2d-6aeab6ae5cae"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard Arrow"",
                    ""id"": ""f8c2fe94-3f3f-4825-865c-ea7e6fb75569"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DetailMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b0fca0d2-ce59-4ef1-a94d-62298a70caf1"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9affe83c-6c3a-4bdd-ad14-20f8b3cdf6df"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8d5eeb11-f368-4b3d-8b52-b76d0087080b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""394a5045-26f3-43e1-8660-339ee28738ee"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""66b7508b-55ca-413a-87a3-26cdffcec544"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DetailMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""abc4f2a5-b6c2-496f-9720-c7ccaf174da1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c9f26ec3-ad67-44c8-8c0c-00f187881d37"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9ab376b9-f664-41c4-b9ad-c235045de1fc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""88401f5d-e45b-4909-9448-4d7f81df9cce"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DetailMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""570fde96-79cf-4374-9f42-f19d91fc2f09"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0475e291-3973-4e37-8f53-420cf7d3b9af"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""MOBILE"",
            ""bindingGroup"": ""MOBILE"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerAction
        m_PlayerAction = asset.FindActionMap("PlayerAction", throwIfNotFound: true);
        m_PlayerAction_Move = m_PlayerAction.FindAction("Move", throwIfNotFound: true);
        m_PlayerAction_Run = m_PlayerAction.FindAction("Run", throwIfNotFound: true);
        m_PlayerAction_Wire = m_PlayerAction.FindAction("Wire", throwIfNotFound: true);
        m_PlayerAction_Assassinate = m_PlayerAction.FindAction("Assassinate", throwIfNotFound: true);
        m_PlayerAction_Crouch = m_PlayerAction.FindAction("Crouch", throwIfNotFound: true);
        m_PlayerAction_Pause = m_PlayerAction.FindAction("Pause", throwIfNotFound: true);
        m_PlayerAction_Aiming = m_PlayerAction.FindAction("Aiming", throwIfNotFound: true);
        m_PlayerAction_Shoot = m_PlayerAction.FindAction("Shoot", throwIfNotFound: true);
        m_PlayerAction_Interaction = m_PlayerAction.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerAction_Clairvoyance = m_PlayerAction.FindAction("Clairvoyance", throwIfNotFound: true);
        m_PlayerAction_GamepadAxis = m_PlayerAction.FindAction("GamepadAxis", throwIfNotFound: true);
        // HideAction
        m_HideAction = asset.FindActionMap("HideAction", throwIfNotFound: true);
        m_HideAction_Peek = m_HideAction.FindAction("Peek", throwIfNotFound: true);
        m_HideAction_Exit = m_HideAction.FindAction("Exit", throwIfNotFound: true);
        m_HideAction_MouseAxis = m_HideAction.FindAction("MouseAxis", throwIfNotFound: true);
        m_HideAction_PeekGamepadAxis = m_HideAction.FindAction("PeekGamepadAxis", throwIfNotFound: true);
        m_HideAction_Pause = m_HideAction.FindAction("Pause", throwIfNotFound: true);
        // SettingAction
        m_SettingAction = asset.FindActionMap("SettingAction", throwIfNotFound: true);
        m_SettingAction_Pause = m_SettingAction.FindAction("Pause", throwIfNotFound: true);
        m_SettingAction_Submit = m_SettingAction.FindAction("Submit", throwIfNotFound: true);
        m_SettingAction_TabMove = m_SettingAction.FindAction("TabMove", throwIfNotFound: true);
        // SettingDetailAction
        m_SettingDetailAction = asset.FindActionMap("SettingDetailAction", throwIfNotFound: true);
        m_SettingDetailAction_DetailSubmit = m_SettingDetailAction.FindAction("DetailSubmit", throwIfNotFound: true);
        m_SettingDetailAction_DetailMove = m_SettingDetailAction.FindAction("DetailMove", throwIfNotFound: true);
        m_SettingDetailAction_Back = m_SettingDetailAction.FindAction("Back", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerAction
    private readonly InputActionMap m_PlayerAction;
    private List<IPlayerActionActions> m_PlayerActionActionsCallbackInterfaces = new List<IPlayerActionActions>();
    private readonly InputAction m_PlayerAction_Move;
    private readonly InputAction m_PlayerAction_Run;
    private readonly InputAction m_PlayerAction_Wire;
    private readonly InputAction m_PlayerAction_Assassinate;
    private readonly InputAction m_PlayerAction_Crouch;
    private readonly InputAction m_PlayerAction_Pause;
    private readonly InputAction m_PlayerAction_Aiming;
    private readonly InputAction m_PlayerAction_Shoot;
    private readonly InputAction m_PlayerAction_Interaction;
    private readonly InputAction m_PlayerAction_Clairvoyance;
    private readonly InputAction m_PlayerAction_GamepadAxis;
    public struct PlayerActionActions
    {
        private @IA_Player m_Wrapper;
        public PlayerActionActions(@IA_Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerAction_Move;
        public InputAction @Run => m_Wrapper.m_PlayerAction_Run;
        public InputAction @Wire => m_Wrapper.m_PlayerAction_Wire;
        public InputAction @Assassinate => m_Wrapper.m_PlayerAction_Assassinate;
        public InputAction @Crouch => m_Wrapper.m_PlayerAction_Crouch;
        public InputAction @Pause => m_Wrapper.m_PlayerAction_Pause;
        public InputAction @Aiming => m_Wrapper.m_PlayerAction_Aiming;
        public InputAction @Shoot => m_Wrapper.m_PlayerAction_Shoot;
        public InputAction @Interaction => m_Wrapper.m_PlayerAction_Interaction;
        public InputAction @Clairvoyance => m_Wrapper.m_PlayerAction_Clairvoyance;
        public InputAction @GamepadAxis => m_Wrapper.m_PlayerAction_GamepadAxis;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActionActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Wire.started += instance.OnWire;
            @Wire.performed += instance.OnWire;
            @Wire.canceled += instance.OnWire;
            @Assassinate.started += instance.OnAssassinate;
            @Assassinate.performed += instance.OnAssassinate;
            @Assassinate.canceled += instance.OnAssassinate;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Aiming.started += instance.OnAiming;
            @Aiming.performed += instance.OnAiming;
            @Aiming.canceled += instance.OnAiming;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @Clairvoyance.started += instance.OnClairvoyance;
            @Clairvoyance.performed += instance.OnClairvoyance;
            @Clairvoyance.canceled += instance.OnClairvoyance;
            @GamepadAxis.started += instance.OnGamepadAxis;
            @GamepadAxis.performed += instance.OnGamepadAxis;
            @GamepadAxis.canceled += instance.OnGamepadAxis;
        }

        private void UnregisterCallbacks(IPlayerActionActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Wire.started -= instance.OnWire;
            @Wire.performed -= instance.OnWire;
            @Wire.canceled -= instance.OnWire;
            @Assassinate.started -= instance.OnAssassinate;
            @Assassinate.performed -= instance.OnAssassinate;
            @Assassinate.canceled -= instance.OnAssassinate;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Aiming.started -= instance.OnAiming;
            @Aiming.performed -= instance.OnAiming;
            @Aiming.canceled -= instance.OnAiming;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @Clairvoyance.started -= instance.OnClairvoyance;
            @Clairvoyance.performed -= instance.OnClairvoyance;
            @Clairvoyance.canceled -= instance.OnClairvoyance;
            @GamepadAxis.started -= instance.OnGamepadAxis;
            @GamepadAxis.performed -= instance.OnGamepadAxis;
            @GamepadAxis.canceled -= instance.OnGamepadAxis;
        }

        public void RemoveCallbacks(IPlayerActionActions instance)
        {
            if (m_Wrapper.m_PlayerActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActionActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActionActions @PlayerAction => new PlayerActionActions(this);

    // HideAction
    private readonly InputActionMap m_HideAction;
    private List<IHideActionActions> m_HideActionActionsCallbackInterfaces = new List<IHideActionActions>();
    private readonly InputAction m_HideAction_Peek;
    private readonly InputAction m_HideAction_Exit;
    private readonly InputAction m_HideAction_MouseAxis;
    private readonly InputAction m_HideAction_PeekGamepadAxis;
    private readonly InputAction m_HideAction_Pause;
    public struct HideActionActions
    {
        private @IA_Player m_Wrapper;
        public HideActionActions(@IA_Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Peek => m_Wrapper.m_HideAction_Peek;
        public InputAction @Exit => m_Wrapper.m_HideAction_Exit;
        public InputAction @MouseAxis => m_Wrapper.m_HideAction_MouseAxis;
        public InputAction @PeekGamepadAxis => m_Wrapper.m_HideAction_PeekGamepadAxis;
        public InputAction @Pause => m_Wrapper.m_HideAction_Pause;
        public InputActionMap Get() { return m_Wrapper.m_HideAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HideActionActions set) { return set.Get(); }
        public void AddCallbacks(IHideActionActions instance)
        {
            if (instance == null || m_Wrapper.m_HideActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HideActionActionsCallbackInterfaces.Add(instance);
            @Peek.started += instance.OnPeek;
            @Peek.performed += instance.OnPeek;
            @Peek.canceled += instance.OnPeek;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
            @MouseAxis.started += instance.OnMouseAxis;
            @MouseAxis.performed += instance.OnMouseAxis;
            @MouseAxis.canceled += instance.OnMouseAxis;
            @PeekGamepadAxis.started += instance.OnPeekGamepadAxis;
            @PeekGamepadAxis.performed += instance.OnPeekGamepadAxis;
            @PeekGamepadAxis.canceled += instance.OnPeekGamepadAxis;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IHideActionActions instance)
        {
            @Peek.started -= instance.OnPeek;
            @Peek.performed -= instance.OnPeek;
            @Peek.canceled -= instance.OnPeek;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
            @MouseAxis.started -= instance.OnMouseAxis;
            @MouseAxis.performed -= instance.OnMouseAxis;
            @MouseAxis.canceled -= instance.OnMouseAxis;
            @PeekGamepadAxis.started -= instance.OnPeekGamepadAxis;
            @PeekGamepadAxis.performed -= instance.OnPeekGamepadAxis;
            @PeekGamepadAxis.canceled -= instance.OnPeekGamepadAxis;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IHideActionActions instance)
        {
            if (m_Wrapper.m_HideActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHideActionActions instance)
        {
            foreach (var item in m_Wrapper.m_HideActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HideActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HideActionActions @HideAction => new HideActionActions(this);

    // SettingAction
    private readonly InputActionMap m_SettingAction;
    private List<ISettingActionActions> m_SettingActionActionsCallbackInterfaces = new List<ISettingActionActions>();
    private readonly InputAction m_SettingAction_Pause;
    private readonly InputAction m_SettingAction_Submit;
    private readonly InputAction m_SettingAction_TabMove;
    public struct SettingActionActions
    {
        private @IA_Player m_Wrapper;
        public SettingActionActions(@IA_Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_SettingAction_Pause;
        public InputAction @Submit => m_Wrapper.m_SettingAction_Submit;
        public InputAction @TabMove => m_Wrapper.m_SettingAction_TabMove;
        public InputActionMap Get() { return m_Wrapper.m_SettingAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SettingActionActions set) { return set.Get(); }
        public void AddCallbacks(ISettingActionActions instance)
        {
            if (instance == null || m_Wrapper.m_SettingActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SettingActionActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @TabMove.started += instance.OnTabMove;
            @TabMove.performed += instance.OnTabMove;
            @TabMove.canceled += instance.OnTabMove;
        }

        private void UnregisterCallbacks(ISettingActionActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @TabMove.started -= instance.OnTabMove;
            @TabMove.performed -= instance.OnTabMove;
            @TabMove.canceled -= instance.OnTabMove;
        }

        public void RemoveCallbacks(ISettingActionActions instance)
        {
            if (m_Wrapper.m_SettingActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISettingActionActions instance)
        {
            foreach (var item in m_Wrapper.m_SettingActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SettingActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SettingActionActions @SettingAction => new SettingActionActions(this);

    // SettingDetailAction
    private readonly InputActionMap m_SettingDetailAction;
    private List<ISettingDetailActionActions> m_SettingDetailActionActionsCallbackInterfaces = new List<ISettingDetailActionActions>();
    private readonly InputAction m_SettingDetailAction_DetailSubmit;
    private readonly InputAction m_SettingDetailAction_DetailMove;
    private readonly InputAction m_SettingDetailAction_Back;
    public struct SettingDetailActionActions
    {
        private @IA_Player m_Wrapper;
        public SettingDetailActionActions(@IA_Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @DetailSubmit => m_Wrapper.m_SettingDetailAction_DetailSubmit;
        public InputAction @DetailMove => m_Wrapper.m_SettingDetailAction_DetailMove;
        public InputAction @Back => m_Wrapper.m_SettingDetailAction_Back;
        public InputActionMap Get() { return m_Wrapper.m_SettingDetailAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SettingDetailActionActions set) { return set.Get(); }
        public void AddCallbacks(ISettingDetailActionActions instance)
        {
            if (instance == null || m_Wrapper.m_SettingDetailActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SettingDetailActionActionsCallbackInterfaces.Add(instance);
            @DetailSubmit.started += instance.OnDetailSubmit;
            @DetailSubmit.performed += instance.OnDetailSubmit;
            @DetailSubmit.canceled += instance.OnDetailSubmit;
            @DetailMove.started += instance.OnDetailMove;
            @DetailMove.performed += instance.OnDetailMove;
            @DetailMove.canceled += instance.OnDetailMove;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
        }

        private void UnregisterCallbacks(ISettingDetailActionActions instance)
        {
            @DetailSubmit.started -= instance.OnDetailSubmit;
            @DetailSubmit.performed -= instance.OnDetailSubmit;
            @DetailSubmit.canceled -= instance.OnDetailSubmit;
            @DetailMove.started -= instance.OnDetailMove;
            @DetailMove.performed -= instance.OnDetailMove;
            @DetailMove.canceled -= instance.OnDetailMove;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
        }

        public void RemoveCallbacks(ISettingDetailActionActions instance)
        {
            if (m_Wrapper.m_SettingDetailActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISettingDetailActionActions instance)
        {
            foreach (var item in m_Wrapper.m_SettingDetailActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SettingDetailActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SettingDetailActionActions @SettingDetailAction => new SettingDetailActionActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    private int m_MOBILESchemeIndex = -1;
    public InputControlScheme MOBILEScheme
    {
        get
        {
            if (m_MOBILESchemeIndex == -1) m_MOBILESchemeIndex = asset.FindControlSchemeIndex("MOBILE");
            return asset.controlSchemes[m_MOBILESchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActionActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnWire(InputAction.CallbackContext context);
        void OnAssassinate(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnAiming(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnClairvoyance(InputAction.CallbackContext context);
        void OnGamepadAxis(InputAction.CallbackContext context);
    }
    public interface IHideActionActions
    {
        void OnPeek(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
        void OnMouseAxis(InputAction.CallbackContext context);
        void OnPeekGamepadAxis(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
    public interface ISettingActionActions
    {
        void OnPause(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnTabMove(InputAction.CallbackContext context);
    }
    public interface ISettingDetailActionActions
    {
        void OnDetailSubmit(InputAction.CallbackContext context);
        void OnDetailMove(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
}
